### ISSUE TITLE
0001908:
Show birthdays in Calendar

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1037] opened 2018-06-08 16:19 UTC
**Reported by linuxq on 23 Nov 2009 07:28**

**Version:** Leonie (2009-07-7)

It would be great if there was a possibility to add the birthdays of the contacts to the calendar automatically!

**Comment by pschuele** [comment] 2018-06-08 18:11
duplicate of #784

**Closed** 2018-06-08 18:11 UTC
Labels: Calendar, Duplicate, Feature Request, Mantis

**Comment by Gloirin** [comment] 2018-06-10 04:58
**Comment posted by Gurney on 15 Oct 2012 13:46**

Duplicate of #1394

**Comment by Gloirin** [comment] 2018-06-10 04:58
**Comment posted by pschuele on 25 Feb 2016 14:58**

hi,
this seems to be a candidate for another community crowdfunding project with all those users monitoring this ...

maybe we&#039;ll add another &quot;target version&quot; for popular feature requests. what do you think?
