### ISSUE TITLE
Error during upgrade from 2018.02.2 to 2018.02.3

### ISSUE THREAD

**Issue by ravermeister** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#45] opened 2018-04-14 22:45 UTC
Hi, when I try to Upgrade tine I get following error: 
my redis module is compiled **without** igbinary support...
```
PHP Fatal error:  Uncaught Error: Undefined class constant 'Redis::SERIALIZER_IGBINARY' in /var/www/virtual/raver/mail.beta.rimkus.it.cur/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php:115
Stack trace:
#0 /var/www/virtual/raver/mail.beta.rimkus.it.cur/vendor/zendframework/zendframework1/library/Zend/Cache.php(153): Zend_Cache_Backend_Redis->__construct(Array)
#1 /var/www/virtual/raver/mail.beta.rimkus.it.cur/vendor/zendframework/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Redis', Array, false, false)
#2 /var/www/virtual/raver/mail.beta.rimkus.it.cur/Tinebase/Core.php(932): Zend_Cache::factory('Core', 'Redis', Array, Array)
#3 /var/www/virtual/raver/mail.beta.rimkus.it.cur/Tinebase/Core.php(1502): Tinebase_Core::setupCache()
#4 /var/www/virtual/raver/mail.beta.rimkus.it.cur/Tinebase/Core.php(985): Tinebase_Core::getCache()
#5 /var/www/virtual/raver/mail.beta.rimkus.it.cur/Setup/Core.php(209): Tinebase_Core::setupDatabaseConnection()
#6 /var/www/virtual/raver/mail.beta.rimkus.it in /var/www/virtual/raver/mail.beta.rimkus.it.cur/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php on line 115
```

what can I do?
currently back on 2018.02.2 and fyi:
```
[raver@indus raver]$ php -v
PHP 7.2.4 (cli) (built: Mar 29 2018 16:28:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by ravermeister** [comment] 2018-04-16 22:58
if you need any further information, please let me know

**Comment by paulmhh** [comment] 2018-04-16 23:04
this version is broken with Redis as backend. It will not be fixed. The next version (2018.02.04) will work again. The library causing the issue is currently not publicly available, but it was planed to move it to github anyway. That might happen next week, then you could just replace the old library version in 2018.02.03 with the most recent version and the issue will be fixed.

We will let you know once the library is available on github

**Comment by shochdoerfer** [comment] 2018-04-17 20:03
Does that mean the whole Tine 2.0 instance is affected by this or is it just the setup part? Can one get it to work in production with 2018.02.03 and Redis or does that simply not work at all?

**Comment by paulmhh** [comment] 2018-04-17 22:42
2018.02.03 with Redis as cache backend should be completely broken and should not be used. Redis as session backend only should probably work (untested).

a work around may be published next week and it will definitely be fixed in the next release

**Comment by shochdoerfer** [comment] 2018-04-18 06:45
Could you then please let us know here when the work-around will be available? I do not want to wait for the next release...

**Comment by pschuele** [comment] 2018-04-18 13:27
you can now download the fixed zf1 version here: https://github.com/tine20/zendframework1/releases/tag/1.12.20pl25

just unzip into tine20/vendor/zendframework/zendframework1

**Closed by pschuele** 2018-04-18 13:27 UTC
Labels: Bug

**Comment by shochdoerfer** [comment] 2018-04-21 10:37
The 1.12.20pl25 version does not work for me, I am getting the same error. Had to use the 1.12.20pl26 version. Unfortunately that is currently not possible to install via Composer due to version conflicts ;(

**Comment by pschuele** [comment] 2018-04-26 09:41
did you try something like this:

    composer require "zendframework/zendframework1 1.12.20pl26 as 1.12.20"

**Comment by shochdoerfer** [comment] 2018-04-26 11:42
I manually changed the line in the composer.json and run composer update which failed due to version conflicts with syncroton or one of it's dependencies IIRC.

**Comment by pschuele** [comment] 2018-05-03 13:41
ah, i think, you should only update zf1. either with "require" or like this:

    composer update zendframework/zendframework1

**Comment by shochdoerfer** [comment] 2018-05-04 20:12
IIRC this is what I tried but will check again.
