### ISSUE TITLE
0002094:
LDAP Anonymous Bind

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1129] opened 2018-06-08 17:06 UTC
**Reported by glyde on 13 Jan 2010 21:09**

**Version:** August (2009-11-3)

In setup, leaving LDAP username and password for anonymous bind generates an empty string for both parameters and stores this in the tine20_config table in the database. Zend uses null to specify anonymous bind in library/Zend/Ldap.php.

**Additional information:** Further details on forum here:
http://www.tine20.org/forum/viewtopic.php?f=8&amp;t=2228

**Comment by pschuele** [comment] 2018-06-08 18:36
duplicate of #872

**Closed by pschuele** 2018-06-08 18:36 UTC
Labels: Bug, Mantis, Setup

**Comment by Gloirin** [comment] 2018-06-10 05:07
**Comment posted by tobi on 20 Jan 2010 12:36**

duplicate:entry  0001570
