### ISSUE TITLE
Unknown column timetracker_timesheet.customfields

### ISSUE THREAD

**Issue by shochdoerfer** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#57] opened 2018-05-09 07:30 UTC
We are using version 2018.02.2 of Tine 2.0. Last week a user was added to Tine 2.0 via LDAP sync. When this user tries to view the timetracking module the following SQL error occurs - the user is not able to search or filter entries:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'timetracker_timesheet.customfields' in 'field list', query was: SELECT timetracker_timesheet.id, timetracker_timesheet.customfields FROM tine20_timetracker_timesheet AS timetracker_timesheet WHERE (timetracker_timesheet.is_deleted = 0) AND ((((timetracker_timesheet.account_id LIKE ('0b05edee-e091-1037-955a-b13bc742bc3d'))) AND ((timetracker_timesheet.timeaccount_id IN ('675423b693b2417d35212cdac96e3be252594727'))))) GROUP BY timetracker_timesheet.id ORDER BY customfields ASC, timetracker_timesheet.creation_time ASC LIMIT 50
.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../Tinebase/Backend/Sql/Abstract.php(772): Zend_Db_Adapter_Pdo_Abstract->query()
.../Tinebase/Backend/Sql/Abstract.php(560): Tinebase_Backend_Sql_Abstract->_fetch()
.../Tinebase/Controller/Record/Abstract.php(243): Tinebase_Backend_Sql_Abstract->search()
.../Tinebase/Frontend/Json/Abstract.php(211): Tinebase_Controller_Record_Abstract->search()
.../Timetracker/Frontend/Json.php(315): Tinebase_Frontend_Json_Abstract->_search()
[internal function]: Timetracker_Frontend_Json->searchTimesheets()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): call_user_func_array()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Tinebase/Server/Json.php(379): Zend_Json_Server->handle()
.../Tinebase/Server/Json.php(163): Tinebase_Server_Json->_handle()
.../Tinebase/Core.php(260): Tinebase_Server_Json->handle()
.../index.php(24): Tinebase_Core::dispatchRequest()
```

This problem only happens when this newly created user is making queries in the timetracking module. For other users this problem seem to not exist. Any idea why is going on here?

Looking in the database the table timetracker_timesheet is missing the customfields column, so technically the error is correct. I am just wondering why this only occurs for this specific user.

**Comment by pschuele** [comment] 2018-05-14 09:59
the problem is that the default sort is set on the customfields column that can't be sorted in that release.
workaround: just set another sort column by clicking the grid header.
this is already fixed in the current master and the upcoming release.

**Closed** 2018-05-14 09:59 UTC
Labels: Timetracker

**Comment by pschuele** [comment] 2018-05-15 08:25
fixed by https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/23019c21932e5b4be91682eb4324e4f9ee53d474

this adds sorting capabilities for customfields: https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/7aca553e519227cbbe3d40a53cad7d001fbbfe2c
