### ISSUE TITLE
0000800:
Make more use of intellegent auto-completion

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#491] opened 2018-06-08 14:06 UTC
**Reported by bbalazs on 7 Feb 2009 23:52**

**Version:** Lara (2009-02) Milestone 2

As a result of user-test: User would like to get more support by intelligent auto-completion. Consider this in every case, where there is a potentially limited number of possible results, e.g. Company-Name, City.

**Comment by pschuele** [comment] 2018-06-08 15:33
duplicate of #289

**Closed by pschuele** 2018-06-08 15:33 UTC
Labels: Mantis, Other

**Comment by Gloirin** [comment] 2018-06-09 20:55
Related to #4388
